(function(){
"use strict";
const D=window.CODEX_DATA;
const homeView=document.getElementById("homeView"),contentView=document.getElementById("contentView"),searchView=document.getElementById("searchView"),contentBody=document.getElementById("contentBody"),breadcrumbs=document.getElementById("breadcrumbs"),searchInput=document.getElementById("searchInput"),searchResults=document.getElementById("searchResults"),stack=[];
function show(v){[homeView,contentView,searchView].forEach(x=>x.classList.remove("active"));v.classList.add("active")}
function home(){stack.length=0;show(homeView)}
function settlement(id){return D.settlements.find(x=>x.id===id)}
function location(id){return D.locations.find(x=>x.id===id)}
function person(id){return D.people.find(x=>x.id===id)}
function tile(t,s,fn){const b=document.createElement("button");b.className="tile-button";b.innerHTML="<strong>"+t+"</strong>"+(s?"<span>"+s+"</span>":"");b.onclick=fn;return b}
function push(v){stack.push(v);render(v)}
function back(){if(stack.length>1){stack.pop();render(stack.at(-1))}else home()}
function art(src,name,portrait){return src?'<img class="entry-art'+(portrait?' portrait':'')+'" src="'+src+'" alt="'+name+'">':'<div class="placeholder">Artwork not yet added</div>'}
function personArt(p){if(p.images?.length){return '<div class="appearance-block"><span>Appearance</span><div id="appearanceControls"></div></div><img id="appearanceImage" class="entry-art portrait" src="'+p.images[0].file+'" alt="'+p.name+' — '+p.images[0].label+'">'}return art(p.image,p.name,true)}
function bindAppearance(p){if(!p.images?.length)return;const c=document.getElementById("appearanceControls"),img=document.getElementById("appearanceImage");p.images.forEach((x,i)=>{const b=document.createElement("button");b.className="appearance-button"+(i===0?" active":"");b.textContent=x.label;b.onclick=()=>{img.src=x.file;img.alt=p.name+" — "+x.label;c.querySelectorAll("button").forEach(q=>q.classList.remove("active"));b.classList.add("active")};c.appendChild(b)})}
function influence(p){return p.influence?'<section class="entry-section influence-section"><h2>Your Influence</h2><p>'+p.influence+'</p></section>':""}
function renderPlaces(){show(contentView);breadcrumbs.textContent="Places";contentBody.innerHTML='<section class="directory"><h2>Places</h2><p>Settlements and landmarks known to the party.</p><div class="directory-list" id="placeList"></div></section>';const list=document.getElementById("placeList");D.settlements.forEach(s=>{const b=document.createElement("button");b.className="directory-button";b.innerHTML="<strong>"+s.name+"</strong><span>"+s.subtitle+"</span>";b.onclick=()=>push({type:"settlement",id:s.id});list.appendChild(b)})}
function renderSettlement(id){const s=settlement(id);show(contentView);breadcrumbs.textContent="Places › "+s.name;contentBody.innerHTML='<article class="entry">'+art(s.image,s.name,false)+'<div class="entry-copy"><div class="kicker">Settlement</div><h1>'+s.name+'</h1><div class="subtitle">'+s.subtitle+'</div><p class="overview">'+s.overview+'</p><section class="entry-section"><h2>Places of Interest</h2><div class="tile-grid" id="locations"></div></section><section class="entry-section"><h2>Notable Residents</h2><div class="tile-grid" id="residents"></div></section></div></article>';const lg=document.getElementById("locations");s.locations.map(location).filter(Boolean).forEach(l=>lg.appendChild(tile(l.name,l.subtitle,()=>push({type:"location",id:l.id}))));const rg=document.getElementById("residents");s.residents.map(person).filter(Boolean).forEach(p=>rg.appendChild(tile(p.name,p.subtitle,()=>push({type:"person",id:p.id}))))}
function renderLocation(id){const l=location(id),s=settlement(l.settlementId);show(contentView);breadcrumbs.textContent="Places › "+s.name+" › "+l.name;contentBody.innerHTML='<article class="entry">'+art(l.image,l.name,false)+'<div class="entry-copy"><div class="kicker">Location</div><h1>'+l.name+'</h1><div class="subtitle">'+l.subtitle+'</div><p class="overview">'+l.overview+'</p><section class="entry-section"><h2>Known Residents</h2><div class="tile-grid" id="residents"></div></section></div></article>';const rg=document.getElementById("residents");l.residents.map(person).filter(Boolean).forEach(p=>rg.appendChild(tile(p.name,p.subtitle,()=>push({type:"person",id:p.id}))))}
function renderPerson(id){const p=person(id),s=settlement(p.settlementId),l=location(p.locationId);show(contentView);breadcrumbs.textContent="Places › "+s.name+(l?" › "+l.name:"")+" › "+p.name;contentBody.innerHTML='<article class="entry">'+personArt(p)+'<div class="entry-copy"><div class="kicker">Person</div><h1>'+p.name+'</h1><div class="subtitle">'+p.subtitle+'</div>'+(p.quote?'<blockquote class="quote">“'+p.quote+'”</blockquote>':'')+'<p class="overview">'+p.overview+'</p><section class="entry-section"><h2>Known Location</h2><div class="tile-grid" id="knownLocation"></div></section>'+(p.associates.length?'<section class="entry-section"><h2>Known Associates</h2><div class="tile-grid" id="associates"></div></section>':'')+influence(p)+'</div></article>';bindAppearance(p);const kl=document.getElementById("knownLocation");kl.appendChild(l?tile(l.name,s.name,()=>push({type:"location",id:l.id})):tile(s.name,s.subtitle,()=>push({type:"settlement",id:s.id})));const ag=document.getElementById("associates");if(ag)p.associates.map(person).filter(Boolean).forEach(a=>ag.appendChild(tile(a.name,a.subtitle,()=>push({type:"person",id:a.id}))))}
function empty(t){show(contentView);breadcrumbs.textContent=t;contentBody.innerHTML='<div class="empty"><div><h2>'+t+'</h2><p>Nothing has been recorded here yet.</p></div></div>'}
function render(v){if(v.type==="places")renderPlaces();else if(v.type==="settlement")renderSettlement(v.id);else if(v.type==="location")renderLocation(v.id);else if(v.type==="person")renderPerson(v.id);else empty(v.title)}
function openSearch(){show(searchView);searchInput.value="";searchResults.innerHTML="";setTimeout(()=>searchInput.focus(),50)}
function search(){const q=searchInput.value.trim().toLowerCase();searchResults.innerHTML="";if(!q)return;const items=[];D.settlements.forEach(x=>{if((x.name+" "+x.subtitle+" "+x.overview).toLowerCase().includes(q))items.push({type:"settlement",item:x})});D.locations.forEach(x=>{if((x.name+" "+x.subtitle+" "+x.overview).toLowerCase().includes(q))items.push({type:"location",item:x})});D.people.forEach(x=>{if((x.name+" "+x.subtitle+" "+x.overview).toLowerCase().includes(q))items.push({type:"person",item:x})});items.forEach(m=>{const b=document.createElement("button");b.className="directory-button";b.innerHTML="<strong>"+m.item.name+"</strong><span>"+m.type+" · "+m.item.subtitle+"</span>";b.onclick=()=>{stack.length=0;stack.push({type:"places"},{type:m.type,id:m.item.id});render(stack.at(-1))};searchResults.appendChild(b)})}
function action(a){if(a==="places"){stack.length=0;stack.push({type:"places"});renderPlaces()}else if(a==="factions"){stack.length=0;stack.push({type:"empty",title:"Factions"});empty("Factions")}else if(a==="history"){stack.length=0;stack.push({type:"empty",title:"History"});empty("History")}else openSearch()}
document.getElementById("homeButton").onclick=home;document.getElementById("placesButton").onclick=()=>action("places");document.getElementById("factionsButton").onclick=()=>action("factions");document.getElementById("historyButton").onclick=()=>action("history");document.getElementById("searchButton").onclick=()=>action("search");document.getElementById("backButton").onclick=back;document.getElementById("closeButton").onclick=home;document.getElementById("closeSearchButton").onclick=home;searchInput.oninput=search;document.querySelectorAll("[data-mobile]").forEach(b=>b.onclick=()=>action(b.dataset.mobile));document.addEventListener("keydown",e=>{if(e.key==="Escape")home()});
})();